# Generated by Django 5.1 on 2024-08-26 01:41

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chataccessattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='expiry_time',
            field=models.DateTimeField(default=chat.models.default_expiry_time),
        ),
    ]
