# Generated by Django 5.1 on 2024-09-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatsession_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
