# Generated by Django 5.1 on 2024-09-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
