# Generated by Django 5.1 on 2024-08-29 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_materials_coursematerial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, related_name='blocked_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
