# Generated by Django 5.1 on 2024-08-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_blocked_students_enrollment_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
